# permissions to do edit serviceinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceinfo-editor-role
rules:
- apiGroups:
  - healthcheck.khc.io
  resources:
  - serviceinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - healthcheck.khc.io
  resources:
  - serviceinfoes/status
  verbs:
  - get
  - patch
  - update
